try{
    harry
}catch(error){
    console.log(error.message)
    console.log(error.name)
    console.log(error.stack)
}finally{
    console.log("progamm runs successfully")
}